# Generated by Django 6.0.2 on 2026-03-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_plan_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Escribe la clave de la materia', max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.IntegerField(blank=True, default=5, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.plan')),
            ],
            options={
                'db_table': 'materias',
            },
        ),
    ]
