# Generated by Django 6.0.2 on 2026-03-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_materia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrera',
            table='carreras',
        ),
    ]
