# Generated by Django 6.0.4 on 2026-07-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20, unique=True, verbose_name='Número de contrato')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tipo_servicio', models.CharField(choices=[('DOMESTICO', 'Doméstico'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('PUBLICO', 'Público')], default='DOMESTICO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario del Servicio',
                'verbose_name_plural': 'Usuarios del Servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
