# Generated by Django 6.0.2 on 2026-03-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.IntegerField(default=10)),
            ],
        ),
    ]
