# Generated by Django 6.0.2 on 2026-03-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(verbose_name=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.carrera')),
            ],
            options={
                'verbose_name_plural': 'Planes de Estudio',
                'db_table': 'planes',
            },
        ),
    ]
