# Generated by Django 6.0.2 on 2026-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
